version: '3.8'
services:
  mariadb:
    container_name: "maria_db"
    image: mariadb:10
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: nncdb
      MARIADB_USER: nnc
      MARIADB_PASSWORD: abcd1234
      MARIADB_ROOT_PASSWORD: 1111
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1111" ]
      interval: 10s
      retries: 5
  application:
    container_name: docker-compose-test
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://maria_db:3306/nncdb
      SPRING_DATASOURCE_USERNAME: "nnc"
      SPRING_DATASOURCE_PASSWORD: "abcd1234"
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./src/main/resources/application.yml:/app/config/application.yml
    command: ["java", "-jar", "app.jar", "--spring.config.location=file:/app/config/application.yml"]
