spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/nncdb
    username: nnc
    password: abcd1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
      dialect: org.hibernate.dialect.MariaDBDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  config: classpath:log4j2-local.xml